name: Testing env
on: workflow_dispatch
env:
  DB_IP: '10.0.0.56'
  IMAGE_NAME: myappimage:latest
jobs:
  jobx:
   env:
     version: '10.5'  
     DB_IP: '192.168.0.100'     
   runs-on: ubuntu-latest
   steps:
   - name: Jobx Step1
     env:
       IMAGE_NAME: nginx
       APPTYPE: IOS
     run: |
        echo "DB_IP is ${{ env.DB_IP }}"
        echo "IMAGE_NAME is ${{ env.IMAGE_NAME }}"
        echo "version is ${{ env.version }}"
   - name: Jobx Step2
     run: |
        echo "DB_IP is ${{ env.DB_IP }}"
        echo "IMAGE_NAME is ${{ env.IMAGE_NAME }}"
        echo "version is ${{ env.version }}"
        