name: Image Build & Push GHCR
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v7
    - name: login to GHCR
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: soujanya1403
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Image Build
      uses: docker/build-push-action@v7
      with:
        context: .
        tags: ghcr.io/soujanya1403/imagex:latest
        push: true        

permission
PAT

==> $GITHUB_TOKEN
==> Uses
==> with 
       


