name: Image Build & Push GHCR
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v7
    - name: Image Build
      uses: docker/build-push-action@v7
      with:
        context: .
        tags: ghcr.io/soujanya1403/imagex:latest
        push: true        

       


